<?php
return [
    'AF' => ['en' => 'Islamic Republic of Afghanistan', 'ru' => 'Исламская Республика Афганистан'],
    'AL' => ['en' => 'Republic of Albania', 'ru' => 'Республика Албания'],
    'DZ' => ['en' => 'People\'s Democratic Republic of Algeria', 'ru' => 'Алжирская Народная Демократическая Республика'],
    'AS' => ['en' => 'American Samoa', 'ru' => 'Американское Самоа'],
    'AD' => ['en' => 'Principality of Andorra', 'ru' => 'Княжество Андорра'],
    'AO' => ['en' => 'Republic of Angola', 'ru' => 'Республика Ангола'],
    'AI' => ['en' => 'Anguilla', 'ru' => 'Ангилья'],
    'AQ' => ['en' => 'Antarctica', 'ru' => 'Антарктида'],
    'AG' => ['en' => 'Antigua and Barbuda', 'ru' => 'Антигуа и Барбуда'],
    'AR' => ['en' => 'Argentine Republic', 'ru' => 'Аргентинская Республика'],
    'AM' => ['en' => 'Republic of Armenia', 'ru' => 'Республика Армения'],
    'AW' => ['en' => 'Aruba', 'ru' => 'Аруба'],
    'AU' => ['en' => 'Commonwealth of Australia', 'ru' => 'Содружество Австралии'],
    'AT' => ['en' => 'Republic of Austria', 'ru' => 'Австрийская Республика'],
    'AZ' => ['en' => 'Republic of Azerbaijan', 'ru' => 'Азербайджанская Республика'],
    'BS' => ['en' => 'Commonwealth of the Bahamas', 'ru' => 'Содружество Багамских Островов'],
    'BH' => ['en' => 'Kingdom of Bahrain', 'ru' => 'Королевство Бахрейн'],
    'BD' => ['en' => 'People\'s Republic of Bangladesh', 'ru' => 'Народная Республика Бангладеш'],
    'BB' => ['en' => 'Barbados', 'ru' => 'Барбадос'],
    'BY' => ['en' => 'Republic of Belarus', 'ru' => 'Республика Беларусь'],
    'BE' => ['en' => 'Kingdom of Belgium', 'ru' => 'Королевство Бельгия'],
    'BZ' => ['en' => 'Belize', 'ru' => 'Белиз'],
    'BJ' => ['en' => 'Republic of Benin', 'ru' => 'Республика Бенин'],
    'BM' => ['en' => 'Bermuda', 'ru' => 'Бермуды'],
    'BT' => ['en' => 'Kingdom of Bhutan', 'ru' => 'Королевство Бутан'],
    'BO' => ['en' => 'Plurinational State of Bolivia', 'ru' => 'Многонациональное Государство Боливия'],
    'BA' => ['en' => 'Bosnia and Herzegovina', 'ru' => 'Босния и Герцеговина'],
    'BW' => ['en' => 'Republic of Botswana', 'ru' => 'Республика Ботсвана'],
    'BR' => ['en' => 'Federative Republic of Brazil', 'ru' => 'Федеративная Республика Бразилия'],
    'BN' => ['en' => 'Brunei Darussalam', 'ru' => 'Бруней-Даруссалам'],
    'BG' => ['en' => 'Republic of Bulgaria', 'ru' => 'Республика Болгария'],
    'BF' => ['en' => 'Burkina Faso', 'ru' => 'Буркина-Фасо'],
    'BI' => ['en' => 'Republic of Burundi', 'ru' => 'Республика Бурунди'],
    'CV' => ['en' => 'Republic of Cabo Verde', 'ru' => 'Республика Кабо-Верде'],
    'KH' => ['en' => 'Kingdom of Cambodia', 'ru' => 'Королевство Камбоджа'],
    'CM' => ['en' => 'Republic of Cameroon', 'ru' => 'Республика Камерун'],
    'CA' => ['en' => 'Canada', 'ru' => 'Канада'],
    'KY' => ['en' => 'Cayman Islands', 'ru' => 'Каймановы Острова'],
    'CF' => ['en' => 'Central African Republic', 'ru' => 'Центральноафриканская Республика'],
    'TD' => ['en' => 'Republic of Chad', 'ru' => 'Республика Чад'],
    'CL' => ['en' => 'Republic of Chile', 'ru' => 'Республика Чили'],
    'CN' => ['en' => 'People\'s Republic of China', 'ru' => 'Китайская Народная Республика'],
    'CO' => ['en' => 'Republic of Colombia', 'ru' => 'Республика Колумбия'],
    'KM' => ['en' => 'Union of the Comoros', 'ru' => 'Союз Коморских Островов'],
    'CG' => ['en' => 'Republic of the Congo', 'ru' => 'Республика Конго'],
    'CD' => ['en' => 'Democratic Republic of the Congo', 'ru' => 'Демократическая Республика Конго'],
    'CK' => ['en' => 'Cook Islands', 'ru' => 'Острова Кука'],
    'CR' => ['en' => 'Republic of Costa Rica', 'ru' => 'Республика Коста-Рика'],
    'CI' => ['en' => 'Republic of Côte d\'Ivoire', 'ru' => 'Республика Кот-д’Ивуар'],
    'HR' => ['en' => 'Republic of Croatia', 'ru' => 'Республика Хорватия'],
    'CU' => ['en' => 'Republic of Cuba', 'ru' => 'Республика Куба'],
    'CY' => ['en' => 'Republic of Cyprus', 'ru' => 'Республика Кипр'],
    'CZ' => ['en' => 'Czech Republic', 'ru' => 'Чешская Республика'],
    'DK' => ['en' => 'Kingdom of Denmark', 'ru' => 'Королевство Дания'],
    'DJ' => ['en' => 'Republic of Djibouti', 'ru' => 'Республика Джибути'],
    'DM' => ['en' => 'Commonwealth of Dominica', 'ru' => 'Содружество Доминики'],
    'DO' => ['en' => 'Dominican Republic', 'ru' => 'Доминиканская Республика'],
    'EC' => ['en' => 'Republic of Ecuador', 'ru' => 'Республика Эквадор'],
    'EG' => ['en' => 'Arab Republic of Egypt', 'ru' => 'Арабская Республика Египет'],
    'SV' => ['en' => 'Republic of El Salvador', 'ru' => 'Республика Эль-Сальвадор'],
    'GQ' => ['en' => 'Republic of Equatorial Guinea', 'ru' => 'Республика Экваториальная Гвинея'],
    'ER' => ['en' => 'State of Eritrea', 'ru' => 'Государство Эритрея'],
    'EE' => ['en' => 'Republic of Estonia', 'ru' => 'Эстонская Республика'],
    'SZ' => ['en' => 'Kingdom of Eswatini', 'ru' => 'Королевство Эсватини'],
    'ET' => ['en' => 'Federal Democratic Republic of Ethiopia', 'ru' => 'Федеративная Демократическая Республика Эфиопия'],
    'FJ' => ['en' => 'Republic of Fiji', 'ru' => 'Республика Фиджи'],
    'FI' => ['en' => 'Republic of Finland', 'ru' => 'Финляндская Республика'],
    'FR' => ['en' => 'French Republic', 'ru' => 'Французская Республика'],
    'GA' => ['en' => 'Gabonese Republic', 'ru' => 'Габонская Республика'],
    'GM' => ['en' => 'Republic of the Gambia', 'ru' => 'Республика Гамбия'],
    'GE' => ['en' => 'Georgia', 'ru' => 'Грузия'],
    'DE' => ['en' => 'Federal Republic of Germany', 'ru' => 'Федеративная Республика Германия'],
    'GH' => ['en' => 'Republic of Ghana', 'ru' => 'Республика Гана'],
    'GR' => ['en' => 'Hellenic Republic', 'ru' => 'Греческая Республика'],
    'GD' => ['en' => 'Grenada', 'ru' => 'Гренада'],
    'GT' => ['en' => 'Republic of Guatemala', 'ru' => 'Республика Гватемала'],
    'GN' => ['en' => 'Republic of Guinea', 'ru' => 'Республика Гвинея'],
    'GW' => ['en' => 'Republic of Guinea-Bissau', 'ru' => 'Республика Гвинея-Бисау'],
    'GY' => ['en' => 'Co-operative Republic of Guyana', 'ru' => 'Кооперативная Республика Гайана'],
    'HT' => ['en' => 'Republic of Haiti', 'ru' => 'Республика Гаити'],
    'HN' => ['en' => 'Republic of Honduras', 'ru' => 'Республика Гондурас'],
    'HU' => ['en' => 'Hungary', 'ru' => 'Венгрия'],
    'IS' => ['en' => 'Republic of Iceland', 'ru' => 'Исландия'],
    'IN' => ['en' => 'Republic of India', 'ru' => 'Республика Индия'],
    'ID' => ['en' => 'Republic of Indonesia', 'ru' => 'Республика Индонезия'],
    'IR' => ['en' => 'Islamic Republic of Iran', 'ru' => 'Исламская Республика Иран'],
    'IQ' => ['en' => 'Republic of Iraq', 'ru' => 'Республика Ирак'],
    'IE' => ['en' => 'Ireland', 'ru' => 'Ирландия'],
    'IL' => ['en' => 'State of Israel', 'ru' => 'Государство Израиль'],
    'IT' => ['en' => 'Italian Republic', 'ru' => 'Итальянская Республика'],
    'JM' => ['en' => 'Jamaica', 'ru' => 'Ямайка'],
    'JP' => ['en' => 'Japan', 'ru' => 'Япония'],
    'JO' => ['en' => 'Hashemite Kingdom of Jordan', 'ru' => 'Иорданское Хашимитское Королевство'],
    'KZ' => ['en' => 'Republic of Kazakhstan', 'ru' => 'Республика Казахстан'],
    'KE' => ['en' => 'Republic of Kenya', 'ru' => 'Республика Кения'],
    'KI' => ['en' => 'Republic of Kiribati', 'ru' => 'Республика Кирибати'],
    'KP' => ['en' => 'Democratic People\'s Republic of Korea', 'ru' => 'Корейская Народно-Демократическая Республика'],
    'KR' => ['en' => 'Republic of Korea', 'ru' => 'Республика Корея'],
    'KW' => ['en' => 'State of Kuwait', 'ru' => 'Государство Кувейт'],
    'KG' => ['en' => 'Kyrgyz Republic', 'ru' => 'Киргизская Республика'],
    'LA' => ['en' => 'Lao People\'s Democratic Republic', 'ru' => 'Лаосская Народно-Демократическая Республика'],
    'LV' => ['en' => 'Republic of Latvia', 'ru' => 'Латвийская Республика'],
    'LB' => ['en' => 'Lebanese Republic', 'ru' => 'Ливанская Республика'],
    'LS' => ['en' => 'Kingdom of Lesotho', 'ru' => 'Королевство Лесото'],
    'LR' => ['en' => 'Republic of Liberia', 'ru' => 'Республика Либерия'],
    'LY' => ['en' => 'State of Libya', 'ru' => 'Государство Ливия'],
    'LI' => ['en' => 'Principality of Liechtenstein', 'ru' => 'Княжество Лихтенштейн'],
    'LT' => ['en' => 'Republic of Lithuania', 'ru' => 'Литовская Республика'],
    'LU' => ['en' => 'Grand Duchy of Luxembourg', 'ru' => 'Великое Герцогство Люксембург'],
    'MG' => ['en' => 'Republic of Madagascar', 'ru' => 'Республика Мадагаскар'],
    'MW' => ['en' => 'Republic of Malawi', 'ru' => 'Республика Малави'],
    'MY' => ['en' => 'Malaysia', 'ru' => 'Малайзия'],
    'MV' => ['en' => 'Republic of Maldives', 'ru' => 'Республика Мальдивы'],
    'ML' => ['en' => 'Republic of Mali', 'ru' => 'Республика Мали'],
    'MT' => ['en' => 'Republic of Malta', 'ru' => 'Республика Мальта'],
    'MH' => ['en' => 'Republic of the Marshall Islands', 'ru' => 'Республика Маршалловы Острова'],
    'MR' => ['en' => 'Islamic Republic of Mauritania', 'ru' => 'Исламская Республика Мавритания'],
    'MU' => ['en' => 'Republic of Mauritius', 'ru' => 'Республика Маврикий'],
    'MX' => ['en' => 'United Mexican States', 'ru' => 'Мексиканские Соединённые Штаты'],
    'FM' => ['en' => 'Federated States of Micronesia', 'ru' => 'Федеративные Штаты Микронезии'],
    'MD' => ['en' => 'Republic of Moldova', 'ru' => 'Республика Молдова'],
    'MC' => ['en' => 'Principality of Monaco', 'ru' => 'Княжество Монако'],
    'MN' => ['en' => 'Mongolia', 'ru' => 'Монголия'],
    'ME' => ['en' => 'Montenegro', 'ru' => 'Черногория'],
    'MA' => ['en' => 'Kingdom of Morocco', 'ru' => 'Королевство Марокко'],
    'MZ' => ['en' => 'Republic of Mozambique', 'ru' => 'Республика Мозамбик'],
    'MM' => ['en' => 'Republic of the Union of Myanmar', 'ru' => 'Республика Союз Мьянма'],
    'NA' => ['en' => 'Republic of Namibia', 'ru' => 'Республика Намибия'],
    'NR' => ['en' => 'Republic of Nauru', 'ru' => 'Республика Науру'],
    'NP' => ['en' => 'Federal Democratic Republic of Nepal', 'ru' => 'Федеративная Демократическая Республика Непал'],
    'NL' => ['en' => 'Kingdom of the Netherlands', 'ru' => 'Королевство Нидерландов'],
    'NZ' => ['en' => 'New Zealand', 'ru' => 'Новая Зеландия'],
    'NI' => ['en' => 'Republic of Nicaragua', 'ru' => 'Республика Никарагуа'],
    'NE' => ['en' => 'Republic of the Niger', 'ru' => 'Республика Нигер'],
    'NG' => ['en' => 'Federal Republic of Nigeria', 'ru' => 'Федеративная Республика Нигерия'],
    'MK' => ['en' => 'Republic of North Macedonia', 'ru' => 'Республика Северная Македония'],
    'NO' => ['en' => 'Kingdom of Norway', 'ru' => 'Королевство Норвегия'],
    'OM' => ['en' => 'Sultanate of Oman', 'ru' => 'Султанат Оман'],
    'PK' => ['en' => 'Islamic Republic of Pakistan', 'ru' => 'Исламская Республика Пакистан'],
    'PW' => ['en' => 'Republic of Palau', 'ru' => 'Республика Палау'],
    'PS' => ['en' => 'State of Palestine', 'ru' => 'Государство Палестина'],
    'PA' => ['en' => 'Republic of Panama', 'ru' => 'Республика Панама'],
    'PG' => ['en' => 'Independent State of Papua New Guinea', 'ru' => 'Независимое Государство Папуа — Новая Гвинея'],
    'PY' => ['en' => 'Republic of Paraguay', 'ru' => 'Республика Парагвай'],
    'PE' => ['en' => 'Republic of Peru', 'ru' => 'Республика Перу'],
    'PH' => ['en' => 'Republic of the Philippines', 'ru' => 'Республика Филиппины'],
    'PL' => ['en' => 'Republic of Poland', 'ru' => 'Республика Польша'],
    'PT' => ['en' => 'Portuguese Republic', 'ru' => 'Португальская Республика'],
    'QA' => ['en' => 'State of Qatar', 'ru' => 'Государство Катар'],
    'RO' => ['en' => 'Romania', 'ru' => 'Румыния'],
    'RU' => ['en' => 'Russian Federation', 'ru' => 'Российская Федерация'],
    'RW' => ['en' => 'Republic of Rwanda', 'ru' => 'Республика Руанда'],
    'KN' => ['en' => 'Federation of Saint Kitts and Nevis', 'ru' => 'Федерация Сент-Китс и Невис'],
    'LC' => ['en' => 'Saint Lucia', 'ru' => 'Сент-Люсия'],
    'VC' => ['en' => 'Saint Vincent and the Grenadines', 'ru' => 'Сент-Винсент и Гренадины'],
    'WS' => ['en' => 'Independent State of Samoa', 'ru' => 'Независимое Государство Самоа'],
    'SM' => ['en' => 'Republic of San Marino', 'ru' => 'Республика Сан-Марино'],
    'ST' => ['en' => 'Democratic Republic of São Tomé and Príncipe', 'ru' => 'Демократическая Республика Сан-Томе и Принсипи'],
    'SA' => ['en' => 'Kingdom of Saudi Arabia', 'ru' => 'Королевство Саудовская Аравия'],
    'SN' => ['en' => 'Republic of Senegal', 'ru' => 'Республика Сенегал'],
    'RS' => ['en' => 'Republic of Serbia', 'ru' => 'Республика Сербия'],
    'SC' => ['en' => 'Republic of Seychelles', 'ru' => 'Республика Сейшельские Острова'],
    'SL' => ['en' => 'Republic of Sierra Leone', 'ru' => 'Республика Сьерра-Леоне'],
    'SG' => ['en' => 'Republic of Singapore', 'ru' => 'Республика Сингапур'],
    'SK' => ['en' => 'Slovak Republic', 'ru' => 'Словацкая Республика'],
    'SI' => ['en' => 'Republic of Slovenia', 'ru' => 'Республика Словения'],
    'SB' => ['en' => 'Solomon Islands', 'ru' => 'Соломоновы Острова'],
    'SO' => ['en' => 'Federal Republic of Somalia', 'ru' => 'Федеративная Республика Сомали'],
    'ZA' => ['en' => 'Republic of South Africa', 'ru' => 'Южно-Африканская Республика'],
    'SS' => ['en' => 'Republic of South Sudan', 'ru' => 'Республика Южный Судан'],
    'ES' => ['en' => 'Kingdom of Spain', 'ru' => 'Королевство Испания'],
    'LK' => ['en' => 'Democratic Socialist Republic of Sri Lanka', 'ru' => 'Демократическая Социалистическая Республика Шри-Ланка'],
    'SD' => ['en' => 'Republic of the Sudan', 'ru' => 'Республика Судан'],
    'SR' => ['en' => 'Republic of Suriname', 'ru' => 'Республика Суринам'],
    'SE' => ['en' => 'Kingdom of Sweden', 'ru' => 'Королевство Швеция'],
    'CH' => ['en' => 'Swiss Confederation', 'ru' => 'Швейцарская Конфедерация'],
    'SY' => ['en' => 'Syrian Arab Republic', 'ru' => 'Сирийская Арабская Республика'],
    'TJ' => ['en' => 'Republic of Tajikistan', 'ru' => 'Республика Таджикистан'],
    'TZ' => ['en' => 'United Republic of Tanzania', 'ru' => 'Объединенная Республика Танзания'],
    'TH' => ['en' => 'Kingdom of Thailand', 'ru' => 'Королевство Таиланд'],
    'TL' => ['en' => 'Democratic Republic of Timor-Leste', 'ru' => 'Демократическая Республика Тимор-Лесте'],
    'TG' => ['en' => 'Togolese Republic', 'ru' => 'Тоголезская Республика'],
    'TO' => ['en' => 'Kingdom of Tonga', 'ru' => 'Королевство Тонга'],
    'TT' => ['en' => 'Republic of Trinidad and Tobago', 'ru' => 'Республика Тринидад и Тобаго'],
    'TN' => ['en' => 'Tunisian Republic', 'ru' => 'Тунисская Республика'],
    'TR' => ['en' => 'Republic of Turkey', 'ru' => 'Республика Турция'],
    'TM' => ['en' => 'Turkmenistan', 'ru' => 'Туркменистан'],
    'TV' => ['en' => 'Tuvalu', 'ru' => 'Тувалу'],
    'UG' => ['en' => 'Republic of Uganda', 'ru' => 'Республика Уганда'],
    'UA' => ['en' => 'Ukraine', 'ru' => 'Украина'],
    'AE' => ['en' => 'United Arab Emirates', 'ru' => 'Объединенные Арабские Эмираты'],
    'GB' => ['en' => 'United Kingdom of Great Britain and Northern Ireland', 'ru' => 'Соединённое Королевство Великобритании и Северной Ирландии'],
    'US' => ['en' => 'United States of America', 'ru' => 'Соединённые Штаты Америки'],
    'UY' => ['en' => 'Oriental Republic of Uruguay', 'ru' => 'Восточная Республика Уругвай'],
    'UZ' => ['en' => 'Republic of Uzbekistan', 'ru' => 'Республика Узбекистан'],
    'VU' => ['en' => 'Republic of Vanuatu', 'ru' => 'Республика Вануату'],
    'VE' => ['en' => 'Bolivarian Republic of Venezuela', 'ru' => 'Боливарианская Республика Венесуэла'],
    'VN' => ['en' => 'Socialist Republic of Vietnam', 'ru' => 'Социалистическая Республика Вьетнам'],
    'YE' => ['en' => 'Republic of Yemen', 'ru' => 'Йеменская Республика'],
    'ZM' => ['en' => 'Republic of Zambia', 'ru' => 'Республика Замбия'],
    'ZW' => ['en' => 'Republic of Zimbabwe', 'ru' => 'Республика Зимбабве'],
];
